<?php
/**
 * AppointmentDetails
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Fulfillment API
 *
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.20.7
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.75
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * AppointmentDetails Class Doc Comment
 *
 * @category Class
 * @description This type contains information used by the installation provider concerning appointment details selected by the buyer
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AppointmentDetails implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'AppointmentDetails';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'appointment_end_time' => 'string',
        'appointment_start_time' => 'string',
        'appointment_status' => 'string',
        'appointment_type' => 'string',
        'appointment_window' => 'string',
        'service_provider_appointment_date' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'appointment_end_time' => null,
        'appointment_start_time' => null,
        'appointment_status' => null,
        'appointment_type' => null,
        'appointment_window' => null,
        'service_provider_appointment_date' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'appointment_end_time' => 'appointmentEndTime',
        'appointment_start_time' => 'appointmentStartTime',
        'appointment_status' => 'appointmentStatus',
        'appointment_type' => 'appointmentType',
        'appointment_window' => 'appointmentWindow',
        'service_provider_appointment_date' => 'serviceProviderAppointmentDate'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'appointment_end_time' => 'setAppointmentEndTime',
        'appointment_start_time' => 'setAppointmentStartTime',
        'appointment_status' => 'setAppointmentStatus',
        'appointment_type' => 'setAppointmentType',
        'appointment_window' => 'setAppointmentWindow',
        'service_provider_appointment_date' => 'setServiceProviderAppointmentDate'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'appointment_end_time' => 'getAppointmentEndTime',
        'appointment_start_time' => 'getAppointmentStartTime',
        'appointment_status' => 'getAppointmentStatus',
        'appointment_type' => 'getAppointmentType',
        'appointment_window' => 'getAppointmentWindow',
        'service_provider_appointment_date' => 'getServiceProviderAppointmentDate'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['appointment_end_time'] = isset($data['appointment_end_time']) ? $data['appointment_end_time'] : null;
        $this->container['appointment_start_time'] = isset($data['appointment_start_time']) ? $data['appointment_start_time'] : null;
        $this->container['appointment_status'] = isset($data['appointment_status']) ? $data['appointment_status'] : null;
        $this->container['appointment_type'] = isset($data['appointment_type']) ? $data['appointment_type'] : null;
        $this->container['appointment_window'] = isset($data['appointment_window']) ? $data['appointment_window'] : null;
        $this->container['service_provider_appointment_date'] = isset($data['service_provider_appointment_date']) ? $data['service_provider_appointment_date'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets appointment_end_time
     *
     * @return string
     */
    public function getAppointmentEndTime()
    {
        return $this->container['appointment_end_time'];
    }

    /**
     * Sets appointment_end_time
     *
     * @param string $appointment_end_time The date and time the appointment ends, formatted as an <a href=\"https://www.iso.org/iso-8601-date-and-time-format.html \" title=\"https://www.iso.org \" target=\"_blank\">ISO 8601</a> string, which is based on the 24-hour Coordinated Universal Time (UTC) clock. Required for tire installation. <br><br><b>Format:</b> <code>[YYYY]-[MM]-[DD]T[hh]:[mm]:[ss].[sss]Z</code> <br><b>Example:</b> <code>2022-10-28T00:00:00.000Z</code>
     *
     * @return $this
     */
    public function setAppointmentEndTime($appointment_end_time)
    {
        $this->container['appointment_end_time'] = $appointment_end_time;

        return $this;
    }

    /**
     * Gets appointment_start_time
     *
     * @return string
     */
    public function getAppointmentStartTime()
    {
        return $this->container['appointment_start_time'];
    }

    /**
     * Sets appointment_start_time
     *
     * @param string $appointment_start_time The date and time the appointment begins, formatted as an <a href=\"https://www.iso.org/iso-8601-date-and-time-format.html \" title=\"https://www.iso.org \" target=\"_blank\">ISO 8601</a> string, which is based on the 24-hour Coordinated Universal Time (UTC) clock.  <br><br><b>Format:</b> <code>[YYYY]-[MM]-[DD]T[hh]:[mm]:[ss].[sss]Z</code> <br><b>Example:</b> <code>2022-10-28T00:10:00.000Z</code>
     *
     * @return $this
     */
    public function setAppointmentStartTime($appointment_start_time)
    {
        $this->container['appointment_start_time'] = $appointment_start_time;

        return $this;
    }

    /**
     * Gets appointment_status
     *
     * @return string
     */
    public function getAppointmentStatus()
    {
        return $this->container['appointment_status'];
    }

    /**
     * Sets appointment_status
     *
     * @param string $appointment_status The status of the appointment. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/fulfillment/types/sel:AppointmentStatusEnum'>eBay API documentation</a>
     *
     * @return $this
     */
    public function setAppointmentStatus($appointment_status)
    {
        $this->container['appointment_status'] = $appointment_status;

        return $this;
    }

    /**
     * Gets appointment_type
     *
     * @return string
     */
    public function getAppointmentType()
    {
        return $this->container['appointment_type'];
    }

    /**
     * Sets appointment_type
     *
     * @param string $appointment_type The type of appointment. MACRO appointments only have a start time (not bounded with end time). TIME_SLOT appointments have a period (both start time and end time). Required for tire installation. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/fulfillment/types/sel:AppointmentTypeEnum'>eBay API documentation</a>
     *
     * @return $this
     */
    public function setAppointmentType($appointment_type)
    {
        $this->container['appointment_type'] = $appointment_type;

        return $this;
    }

    /**
     * Gets appointment_window
     *
     * @return string
     */
    public function getAppointmentWindow()
    {
        return $this->container['appointment_window'];
    }

    /**
     * Sets appointment_window
     *
     * @param string $appointment_window Appointment window for MACRO appointments. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/fulfillment/types/sel:AppointmentWindowEnum'>eBay API documentation</a>
     *
     * @return $this
     */
    public function setAppointmentWindow($appointment_window)
    {
        $this->container['appointment_window'] = $appointment_window;

        return $this;
    }

    /**
     * Gets service_provider_appointment_date
     *
     * @return string
     */
    public function getServiceProviderAppointmentDate()
    {
        return $this->container['service_provider_appointment_date'];
    }

    /**
     * Sets service_provider_appointment_date
     *
     * @param string $service_provider_appointment_date Service provider date of the appointment (no time stamp). Returned only for MACRO appointment types.
     *
     * @return $this
     */
    public function setServiceProviderAppointmentDate($service_provider_appointment_date)
    {
        $this->container['service_provider_appointment_date'] = $service_provider_appointment_date;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
