<?php
/**
 * Buyer
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Fulfillment API
 *
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.20.7
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.75
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * Buyer Class Doc Comment
 *
 * @category Class
 * @description This type contains information about the order&#x27;s buyer.
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Buyer implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'Buyer';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'buyer_registration_address' => '\Swagger\Client\Model\ExtendedContact',
        'tax_address' => '\Swagger\Client\Model\TaxAddress',
        'tax_identifier' => '\Swagger\Client\Model\TaxIdentifier',
        'username' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'buyer_registration_address' => null,
        'tax_address' => null,
        'tax_identifier' => null,
        'username' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'buyer_registration_address' => 'buyerRegistrationAddress',
        'tax_address' => 'taxAddress',
        'tax_identifier' => 'taxIdentifier',
        'username' => 'username'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'buyer_registration_address' => 'setBuyerRegistrationAddress',
        'tax_address' => 'setTaxAddress',
        'tax_identifier' => 'setTaxIdentifier',
        'username' => 'setUsername'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'buyer_registration_address' => 'getBuyerRegistrationAddress',
        'tax_address' => 'getTaxAddress',
        'tax_identifier' => 'getTaxIdentifier',
        'username' => 'getUsername'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['buyer_registration_address'] = isset($data['buyer_registration_address']) ? $data['buyer_registration_address'] : null;
        $this->container['tax_address'] = isset($data['tax_address']) ? $data['tax_address'] : null;
        $this->container['tax_identifier'] = isset($data['tax_identifier']) ? $data['tax_identifier'] : null;
        $this->container['username'] = isset($data['username']) ? $data['username'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets buyer_registration_address
     *
     * @return \Swagger\Client\Model\ExtendedContact
     */
    public function getBuyerRegistrationAddress()
    {
        return $this->container['buyer_registration_address'];
    }

    /**
     * Sets buyer_registration_address
     *
     * @param \Swagger\Client\Model\ExtendedContact $buyer_registration_address buyer_registration_address
     *
     * @return $this
     */
    public function setBuyerRegistrationAddress($buyer_registration_address)
    {
        $this->container['buyer_registration_address'] = $buyer_registration_address;

        return $this;
    }

    /**
     * Gets tax_address
     *
     * @return \Swagger\Client\Model\TaxAddress
     */
    public function getTaxAddress()
    {
        return $this->container['tax_address'];
    }

    /**
     * Sets tax_address
     *
     * @param \Swagger\Client\Model\TaxAddress $tax_address tax_address
     *
     * @return $this
     */
    public function setTaxAddress($tax_address)
    {
        $this->container['tax_address'] = $tax_address;

        return $this;
    }

    /**
     * Gets tax_identifier
     *
     * @return \Swagger\Client\Model\TaxIdentifier
     */
    public function getTaxIdentifier()
    {
        return $this->container['tax_identifier'];
    }

    /**
     * Sets tax_identifier
     *
     * @param \Swagger\Client\Model\TaxIdentifier $tax_identifier tax_identifier
     *
     * @return $this
     */
    public function setTaxIdentifier($tax_identifier)
    {
        $this->container['tax_identifier'] = $tax_identifier;

        return $this;
    }

    /**
     * Gets username
     *
     * @return string
     */
    public function getUsername()
    {
        return $this->container['username'];
    }

    /**
     * Sets username
     *
     * @param string $username The buyer's eBay user ID.
     *
     * @return $this
     */
    public function setUsername($username)
    {
        $this->container['username'] = $username;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
