<?php
/**
 * Program
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Fulfillment API
 *
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.20.7
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.75
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * Program Class Doc Comment
 *
 * @category Class
 * @description This type is returned for order line items eligible for the Authenticity Guarantee service and/or for order line items fulfilled by the eBay Fulfillment program or eBay shipping.
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Program implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'Program';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'authenticity_verification' => '\Swagger\Client\Model\PostSaleAuthenticationProgram',
        'ebay_shipping' => '\Swagger\Client\Model\EbayShipping',
        'ebay_vault' => '\Swagger\Client\Model\EbayVaultProgram',
        'ebay_international_shipping' => '\Swagger\Client\Model\EbayInternationalShipping',
        'fulfillment_program' => '\Swagger\Client\Model\EbayFulfillmentProgram'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'authenticity_verification' => null,
        'ebay_shipping' => null,
        'ebay_vault' => null,
        'ebay_international_shipping' => null,
        'fulfillment_program' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'authenticity_verification' => 'authenticityVerification',
        'ebay_shipping' => 'ebayShipping',
        'ebay_vault' => 'ebayVault',
        'ebay_international_shipping' => 'ebayInternationalShipping',
        'fulfillment_program' => 'fulfillmentProgram'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'authenticity_verification' => 'setAuthenticityVerification',
        'ebay_shipping' => 'setEbayShipping',
        'ebay_vault' => 'setEbayVault',
        'ebay_international_shipping' => 'setEbayInternationalShipping',
        'fulfillment_program' => 'setFulfillmentProgram'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'authenticity_verification' => 'getAuthenticityVerification',
        'ebay_shipping' => 'getEbayShipping',
        'ebay_vault' => 'getEbayVault',
        'ebay_international_shipping' => 'getEbayInternationalShipping',
        'fulfillment_program' => 'getFulfillmentProgram'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['authenticity_verification'] = isset($data['authenticity_verification']) ? $data['authenticity_verification'] : null;
        $this->container['ebay_shipping'] = isset($data['ebay_shipping']) ? $data['ebay_shipping'] : null;
        $this->container['ebay_vault'] = isset($data['ebay_vault']) ? $data['ebay_vault'] : null;
        $this->container['ebay_international_shipping'] = isset($data['ebay_international_shipping']) ? $data['ebay_international_shipping'] : null;
        $this->container['fulfillment_program'] = isset($data['fulfillment_program']) ? $data['fulfillment_program'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets authenticity_verification
     *
     * @return \Swagger\Client\Model\PostSaleAuthenticationProgram
     */
    public function getAuthenticityVerification()
    {
        return $this->container['authenticity_verification'];
    }

    /**
     * Sets authenticity_verification
     *
     * @param \Swagger\Client\Model\PostSaleAuthenticationProgram $authenticity_verification authenticity_verification
     *
     * @return $this
     */
    public function setAuthenticityVerification($authenticity_verification)
    {
        $this->container['authenticity_verification'] = $authenticity_verification;

        return $this;
    }

    /**
     * Gets ebay_shipping
     *
     * @return \Swagger\Client\Model\EbayShipping
     */
    public function getEbayShipping()
    {
        return $this->container['ebay_shipping'];
    }

    /**
     * Sets ebay_shipping
     *
     * @param \Swagger\Client\Model\EbayShipping $ebay_shipping ebay_shipping
     *
     * @return $this
     */
    public function setEbayShipping($ebay_shipping)
    {
        $this->container['ebay_shipping'] = $ebay_shipping;

        return $this;
    }

    /**
     * Gets ebay_vault
     *
     * @return \Swagger\Client\Model\EbayVaultProgram
     */
    public function getEbayVault()
    {
        return $this->container['ebay_vault'];
    }

    /**
     * Sets ebay_vault
     *
     * @param \Swagger\Client\Model\EbayVaultProgram $ebay_vault ebay_vault
     *
     * @return $this
     */
    public function setEbayVault($ebay_vault)
    {
        $this->container['ebay_vault'] = $ebay_vault;

        return $this;
    }

    /**
     * Gets ebay_international_shipping
     *
     * @return \Swagger\Client\Model\EbayInternationalShipping
     */
    public function getEbayInternationalShipping()
    {
        return $this->container['ebay_international_shipping'];
    }

    /**
     * Sets ebay_international_shipping
     *
     * @param \Swagger\Client\Model\EbayInternationalShipping $ebay_international_shipping ebay_international_shipping
     *
     * @return $this
     */
    public function setEbayInternationalShipping($ebay_international_shipping)
    {
        $this->container['ebay_international_shipping'] = $ebay_international_shipping;

        return $this;
    }

    /**
     * Gets fulfillment_program
     *
     * @return \Swagger\Client\Model\EbayFulfillmentProgram
     */
    public function getFulfillmentProgram()
    {
        return $this->container['fulfillment_program'];
    }

    /**
     * Sets fulfillment_program
     *
     * @param \Swagger\Client\Model\EbayFulfillmentProgram $fulfillment_program fulfillment_program
     *
     * @return $this
     */
    public function setFulfillmentProgram($fulfillment_program)
    {
        $this->container['fulfillment_program'] = $fulfillment_program;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
