<?php
/**
 * BuyerTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Fulfillment API
 *
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.20.7
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.75
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * BuyerTest Class Doc Comment
 *
 * @category    Class
 * @description This type contains information about the order&#x27;s buyer.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BuyerTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Buyer"
     */
    public function testBuyer()
    {
    }

    /**
     * Test attribute "buyer_registration_address"
     */
    public function testPropertyBuyerRegistrationAddress()
    {
    }

    /**
     * Test attribute "tax_address"
     */
    public function testPropertyTaxAddress()
    {
    }

    /**
     * Test attribute "tax_identifier"
     */
    public function testPropertyTaxIdentifier()
    {
    }

    /**
     * Test attribute "username"
     */
    public function testPropertyUsername()
    {
    }
}
