<?php
/**
 * EvidenceRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Fulfillment API
 *
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.20.7
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.75
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * EvidenceRequestTest Class Doc Comment
 *
 * @category    Class
 * @description This type is used by the &lt;strong&gt;evidenceRequests&lt;/strong&gt; array that is returned in the &lt;strong&gt;getPaymentDispute&lt;/strong&gt; response if one or more evidential documents are being requested to help resolve the payment dispute.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EvidenceRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "EvidenceRequest"
     */
    public function testEvidenceRequest()
    {
    }

    /**
     * Test attribute "evidence_id"
     */
    public function testPropertyEvidenceId()
    {
    }

    /**
     * Test attribute "evidence_type"
     */
    public function testPropertyEvidenceType()
    {
    }

    /**
     * Test attribute "line_items"
     */
    public function testPropertyLineItems()
    {
    }

    /**
     * Test attribute "request_date"
     */
    public function testPropertyRequestDate()
    {
    }

    /**
     * Test attribute "respond_by_date"
     */
    public function testPropertyRespondByDate()
    {
    }
}
