<?php
/**
 * LineItemFulfillmentInstructionsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Fulfillment API
 *
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.20.7
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.75
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * LineItemFulfillmentInstructionsTest Class Doc Comment
 *
 * @category    Class
 * @description This type contains the specifications for processing the fulfillment of a line item, including the handling window and the delivery window. These fields provide guidance for &lt;i&gt;eBay Guaranteed Delivery&lt;/i&gt; as well as for non-guaranteed delivery.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LineItemFulfillmentInstructionsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "LineItemFulfillmentInstructions"
     */
    public function testLineItemFulfillmentInstructions()
    {
    }

    /**
     * Test attribute "guaranteed_delivery"
     */
    public function testPropertyGuaranteedDelivery()
    {
    }

    /**
     * Test attribute "max_estimated_delivery_date"
     */
    public function testPropertyMaxEstimatedDeliveryDate()
    {
    }

    /**
     * Test attribute "min_estimated_delivery_date"
     */
    public function testPropertyMinEstimatedDeliveryDate()
    {
    }

    /**
     * Test attribute "ship_by_date"
     */
    public function testPropertyShipByDate()
    {
    }
}
