<?php
/**
 * LineItemPropertiesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Fulfillment API
 *
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.20.7
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.75
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * LineItemPropertiesTest Class Doc Comment
 *
 * @category    Class
 * @description This type contains information about the eBay programs under which a line item was listed and sold.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LineItemPropertiesTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "LineItemProperties"
     */
    public function testLineItemProperties()
    {
    }

    /**
     * Test attribute "buyer_protection"
     */
    public function testPropertyBuyerProtection()
    {
    }

    /**
     * Test attribute "from_best_offer"
     */
    public function testPropertyFromBestOffer()
    {
    }

    /**
     * Test attribute "sold_via_ad_campaign"
     */
    public function testPropertySoldViaAdCampaign()
    {
    }
}
