<?php
/**
 * OrderTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Fulfillment API
 *
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.20.7
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.75
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * OrderTest Class Doc Comment
 *
 * @category    Class
 * @description This type contains the details of an order, including information about the buyer, order history, shipping fulfillments, line items, costs, payments, and order fulfillment status.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OrderTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Order"
     */
    public function testOrder()
    {
    }

    /**
     * Test attribute "buyer"
     */
    public function testPropertyBuyer()
    {
    }

    /**
     * Test attribute "buyer_checkout_notes"
     */
    public function testPropertyBuyerCheckoutNotes()
    {
    }

    /**
     * Test attribute "cancel_status"
     */
    public function testPropertyCancelStatus()
    {
    }

    /**
     * Test attribute "creation_date"
     */
    public function testPropertyCreationDate()
    {
    }

    /**
     * Test attribute "ebay_collect_and_remit_tax"
     */
    public function testPropertyEbayCollectAndRemitTax()
    {
    }

    /**
     * Test attribute "fulfillment_hrefs"
     */
    public function testPropertyFulfillmentHrefs()
    {
    }

    /**
     * Test attribute "fulfillment_start_instructions"
     */
    public function testPropertyFulfillmentStartInstructions()
    {
    }

    /**
     * Test attribute "last_modified_date"
     */
    public function testPropertyLastModifiedDate()
    {
    }

    /**
     * Test attribute "line_items"
     */
    public function testPropertyLineItems()
    {
    }

    /**
     * Test attribute "order_fulfillment_status"
     */
    public function testPropertyOrderFulfillmentStatus()
    {
    }

    /**
     * Test attribute "order_id"
     */
    public function testPropertyOrderId()
    {
    }

    /**
     * Test attribute "order_payment_status"
     */
    public function testPropertyOrderPaymentStatus()
    {
    }

    /**
     * Test attribute "payment_summary"
     */
    public function testPropertyPaymentSummary()
    {
    }

    /**
     * Test attribute "pricing_summary"
     */
    public function testPropertyPricingSummary()
    {
    }

    /**
     * Test attribute "program"
     */
    public function testPropertyProgram()
    {
    }

    /**
     * Test attribute "sales_record_reference"
     */
    public function testPropertySalesRecordReference()
    {
    }

    /**
     * Test attribute "seller_id"
     */
    public function testPropertySellerId()
    {
    }

    /**
     * Test attribute "total_fee_basis_amount"
     */
    public function testPropertyTotalFeeBasisAmount()
    {
    }

    /**
     * Test attribute "total_marketplace_fee"
     */
    public function testPropertyTotalMarketplaceFee()
    {
    }
}
