<?php
/**
 * PaymentDisputeOutcomeDetailTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Fulfillment API
 *
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.20.7
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.75
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * PaymentDisputeOutcomeDetailTest Class Doc Comment
 *
 * @category    Class
 * @description This type is used by the &lt;strong&gt;resolution&lt;/strong&gt; container that is returned for payment disputes that have been resolved.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PaymentDisputeOutcomeDetailTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PaymentDisputeOutcomeDetail"
     */
    public function testPaymentDisputeOutcomeDetail()
    {
    }

    /**
     * Test attribute "fees"
     */
    public function testPropertyFees()
    {
    }

    /**
     * Test attribute "protected_amount"
     */
    public function testPropertyProtectedAmount()
    {
    }

    /**
     * Test attribute "protection_status"
     */
    public function testPropertyProtectionStatus()
    {
    }

    /**
     * Test attribute "reason_for_closure"
     */
    public function testPropertyReasonForClosure()
    {
    }

    /**
     * Test attribute "recoup_amount"
     */
    public function testPropertyRecoupAmount()
    {
    }

    /**
     * Test attribute "total_fee_credit"
     */
    public function testPropertyTotalFeeCredit()
    {
    }
}
