<?php
/**
 * PaymentDisputeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Fulfillment API
 *
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.20.7
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.75
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * PaymentDisputeTest Class Doc Comment
 *
 * @category    Class
 * @description This type is used by the base response of the &lt;strong&gt;getPaymentDispute&lt;/strong&gt; method. The &lt;strong&gt;getPaymentDispute&lt;/strong&gt; method retrieves detailed information on a specific payment dispute.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PaymentDisputeTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PaymentDispute"
     */
    public function testPaymentDispute()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "available_choices"
     */
    public function testPropertyAvailableChoices()
    {
    }

    /**
     * Test attribute "buyer_provided"
     */
    public function testPropertyBuyerProvided()
    {
    }

    /**
     * Test attribute "buyer_username"
     */
    public function testPropertyBuyerUsername()
    {
    }

    /**
     * Test attribute "closed_date"
     */
    public function testPropertyClosedDate()
    {
    }

    /**
     * Test attribute "evidence"
     */
    public function testPropertyEvidence()
    {
    }

    /**
     * Test attribute "evidence_requests"
     */
    public function testPropertyEvidenceRequests()
    {
    }

    /**
     * Test attribute "line_items"
     */
    public function testPropertyLineItems()
    {
    }

    /**
     * Test attribute "monetary_transactions"
     */
    public function testPropertyMonetaryTransactions()
    {
    }

    /**
     * Test attribute "note"
     */
    public function testPropertyNote()
    {
    }

    /**
     * Test attribute "open_date"
     */
    public function testPropertyOpenDate()
    {
    }

    /**
     * Test attribute "order_id"
     */
    public function testPropertyOrderId()
    {
    }

    /**
     * Test attribute "payment_dispute_id"
     */
    public function testPropertyPaymentDisputeId()
    {
    }

    /**
     * Test attribute "payment_dispute_status"
     */
    public function testPropertyPaymentDisputeStatus()
    {
    }

    /**
     * Test attribute "reason"
     */
    public function testPropertyReason()
    {
    }

    /**
     * Test attribute "resolution"
     */
    public function testPropertyResolution()
    {
    }

    /**
     * Test attribute "respond_by_date"
     */
    public function testPropertyRespondByDate()
    {
    }

    /**
     * Test attribute "return_address"
     */
    public function testPropertyReturnAddress()
    {
    }

    /**
     * Test attribute "revision"
     */
    public function testPropertyRevision()
    {
    }

    /**
     * Test attribute "seller_response"
     */
    public function testPropertySellerResponse()
    {
    }
}
